### ISSUE TITLE
Make project adhere to object oriented practices

### ISSUE THREAD

**Issue by lcsfrey** [cs361fall2017/team2#38] opened 2017-11-06 00:44 UTC
OOP practices dictate that all classes should try to serve one purpose within the program. Currently, most of the logic, functionality, and UI processing of the game is within the Game.java file. The file should be split up into a Deck, Board, and Game class.
- The Deck handles the building, shuffling, and distribution of cards.
- The Board handles the moving and removing cards from play, as well as getting cards from the Deck.
- The Game handles the concrete rules of Aces Up, deciding IF a card can be moved or removed, as well as maintaining the score and the state of the game.
- All UI processing should either be done in the Application Controller or on the javascript side.

**Comment by AntonSynytsiaOSU** [comment] 2017-11-09 05:57
The issue is addressed by pull request #40 and #43.

**Closed** 2017-11-09 06:48 UTC
